//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApp.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public string EngineerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Address { get; set; }
        public string Locality { get; set; }
        public string SubLocality { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Fare { get; set; }
        public Nullable<int> NoOfCustAttain { get; set; }
        public Nullable<int> AvgRating { get; set; }
        public int ServiceTypeID { get; set; }
    
        public virtual ServiceTypeMaster ServiceTypeMaster { get; set; }
    }
}
