//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApp.Domain.DataModel
{
    using System;
    
    public partial class EngineerRequestResponseAPI
    {
        public string ServiceRequestNO { get; set; }
        public string ServiceCategoryName { get; set; }
        public string ServiceTypeName { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string StatusTypeName { get; set; }
        public int StatusTypeID { get; set; }
        public string Landmark { get; set; }
        public string Remark { get; set; }
    }
}
