//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApp.Domain.DataModel
{
    using System;
    
    public partial class EngineerRequestResponse
    {
        public int StatusTypeID { get; set; }
        public string SRNO { get; set; }
        public string SRCategory { get; set; }
        public string SRTYPE { get; set; }
        public string Customer_Name { get; set; }
        public System.DateTime Created_DateTime { get; set; }
        public Nullable<System.DateTime> Assigned_DateTime { get; set; }
        public Nullable<System.DateTime> Completed_DateTime { get; set; }
        public string Customer_Feedback { get; set; }
        public string Status { get; set; }
    }
}
