//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApp.Domain.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceAppDBContext : DbContext
    {
        public ServiceAppDBContext()
            : base("name=ServiceAppDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<Engineer> Engineers { get; set; }
        public virtual DbSet<EngineerMembership> EngineerMemberships { get; set; }
        public virtual DbSet<ServiceTypeMaster> ServiceTypeMasters { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
