//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApp.Domain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        public int ServiceRequestID { get; set; }
        public int ServiceTypeID { get; set; }
        public int StatusTypeID { get; set; }
        public string Landmark { get; set; }
        public string Remark { get; set; }
        public string ServiceRequestRemark { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> EngineerConfirmDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ServiceTypeMaster ServiceTypeMaster { get; set; }
        public virtual StatusTypeMaster StatusTypeMaster { get; set; }
    }
}
